### PR TITLE
mutter: fix dependencies, remove unneeded patch

### PR DESCRIPTION
**Pull request by lazyape**

### CODE REVIEW

**Comment by v4hn** [comment]
No.

why would you remove meson as a dependency for a meson-based build?

The patch (as the name says) is required if you switch *off* libwacom.
It will be part of the next release which is not yet available.

**Comment by lazyape** [comment]
patch is already land on mutter-3.36.2 tarball
https://gitlab.gnome.org/GNOME/mutter/-/blame/gnome-3-36/src/backends/x11/meta-input-device-x11.c#L125

meson is a hard dependency for other packages that mutter is depended on (i.e gdk-pixbuf).
for me there is no need to add it as hard dependency to others as well. otherwise we should
add gtk+-3 to all the modules that needs it

**Comment by v4hn** [comment]
> patch is already land on mutter-3.36.2 tarball

True, I did not update my moonbase-gnome3 when checking, sorry.

> meson is a hard dependency for other packages that mutter is depended on (i.e gdk-pixbuf).
> for me there is no need to add it as hard dependency to others as well. otherwise we should
> add gtk+-3 to all the modules that needs it

This line of argumentation was discussed in lunar a number of times before.
A package should depend on everything it actually requires and tests for itself.

If you find gtk+-3 checks in some build config and the dependency is not listed, it should, indeed, be added there.

**Comment by v4hn** [comment]
implemented in 29a7b0485d7a19d6f36b4b7044943b815413bc9a

**Comment by lazyape** [comment]
```If you find gtk+-3 checks in some build config and the dependency is not listed, it should, indeed, be added there```

for example mutter. if we search for dependency in the meson files we will see that currently
there are 61 entries...
grep -r \ dependency mutter-3.36.2/|grep meson|cut -d\= -f2|sort|uniq

even if we know that one package installs 2 or more of those dependencies we will end up with
at least 50 dependencies for mutter which is indeed true, but the list can be shrinked down without
having problem with it.

assuming the following schema
A->B
B->C

cat C/DEPENDS
depends B

seems more reasonable to me. without B C cannot be built.

**Pull request closed without merging**
