### PR TITLE
webkit2gtk3: prevent compilation if LANG is not utf8 compatible

### PR DESCRIPTION
**Pull request by lazyape**
according to https://github.com/lunar-linux/moonbase-gnome3/issues/117
LANG and LC_CTYPE need to have a value of the form <lang>.utf8 else
some python2 scripts fails due to unicode error

### CODE REVIEW

**Comment by v4hn** [comment]
You accidentally committed files in `libs` instead of `libs/webkit2gtk3`.

Did you test whether it suffices to add
```
export LANG=en_US.utf8
export LC_CTYPES=en_US.utf8
```
in the beginning of the `BUILD` file?

**Comment by lazyape** [comment]
thanks for the info V4hn, i haven't notice that i pushed on libs instead of webkit2gtk3 dir.
I don't think it is a good idea to "force" en_US.utf8. i am using for example el_GR.utf8.
one possible solution is to "force" the .utf8 in case the initial value does not have it
but we will have to also add checks about the value, i mean
there is no point in adding .utf8 if initial value is THIS_IS_A_WRONG_LANG_VALUE

**Comment by lazyape** [comment]
recheck

**Comment by lazyape** [comment]
retest

**Comment by lazyape** [comment]
retest this please

**Pull request closed without merging**
